x-app: &app
  restart: unless-stopped

services:
  frontend:
    image: ghcr.io/aleksioprime/sk-diagnostics-frontend:${FRONTEND_IMAGE_TAG:-latest}
    <<: *app
    container_name: sk-diagnostics-frontend
    networks:
      - apps_net

networks:
  apps_net:
    external: true
